@startuml

title Dummy
hide stereotype
skinparam Arrow {
Color #555555
FontColor #555555
}
skinparam UseCase {
BackgroundColor #FFFFCC
BorderColor #555555
}

skinparam UseCase {
BackgroundColor<< Dummy >> #FFFFCC
}
(init)<< Dummy >>
(composer)<< Dummy >>
(tests)<< Dummy >>
(notifying)<< Dummy >>
(emailing)<< Dummy >>
(irc)<< Dummy >>
(phpunit)<< Dummy >>
(behat)<< Dummy >>


(init) --> (composer) : depend:1
(tests) --> (phpunit) : call:1
(tests) --> (behat) : call:2
(tests) --> (composer) : depend:1
(notifying) --> (emailing) : call:1
(notifying) --> (irc) : call:2
(notifying) --> (composer) : depend:1
@enduml
