@startuml

title ProjectName
hide stereotype
skinparam Arrow {
Color #555555
FontColor #555555
}
skinparam UseCase {
BackgroundColor #FFFFCC
BorderColor #555555
}

skinparam UseCase {
BackgroundColor<< ProjectName >> #FFFFCC
}
(build)<< ProjectName >>
(start)<< ProjectName >>
(clean)<< ProjectName >>
(composer)<< ProjectName >>
(phpdoc)<< ProjectName >>
(makedist)<< ProjectName >>
(structure)<< ProjectName >>
(phpunit)<< ProjectName >>
(metrics)<< ProjectName >>
(copylogs)<< ProjectName >>
(deploy)<< ProjectName >>


(build) --> (start) : call:1
(build) --> (clean) : call:2
(build) --> (structure) : call:3
(build) --> (composer) : call:4
(build) --> (phpunit) : call:5
(build) --> (metrics) : call:6
(build) --> (phpdoc) : call:7
(build) --> (copylogs) : call:8
(build) --> (makedist) : call:9
(build) --> (deploy) : call:10
@enduml
