@startuml

title HelloWorld
skinparam ArrowFontColor Black
skinparam ArrowThickness 2
skinparam UseCaseBackgroundColor #FFFECC
skinparam UseCaseBorderColor #333333
skinparam UseCaseBorderThickness 2
skinparam UseCaseFontColor Black

(welcome)
(test)
(build)


(build) -[#5D9CEC]-> (test) : depend:1

@enduml
