@startuml

skinparam Arrow {
Color #0C3A49
FontColor #3787A6
}
skinparam Usecase {
BackgroundColor #F7FEE1
BorderColor #0C3A49
}

rectangle "stream" {
(main)
(init)
(test)
(phpmd)
(phpcpd)
}

(main) --> (init) : depend:1
(main) --> (phpmd) : depend:2
(main) --> (phpcpd) : depend:3
(main) --> (test) : depend:4
@enduml
