@startuml

title stream
hide stereotype
skinparam Arrow {
Color #555555
FontColor #555555
}
skinparam UseCase {
BackgroundColor #FFFFCC
BorderColor #555555
}

skinparam UseCase {
BackgroundColor<< stream >> #FFFFCC
}
(main)<< stream >>
(init)<< stream >>
(test)<< stream >>
(phpmd)<< stream >>
(phpcpd)<< stream >>


(main) --> (init) : depend:1
(main) --> (phpmd) : depend:2
(main) --> (phpcpd) : depend:3
(main) --> (test) : depend:4
@enduml
