@startuml

title HelloWorld
hide stereotype
skinparam Arrow {
Color #555555
FontColor #555555
}
skinparam UseCase {
BackgroundColor #FFFFCC
BorderColor #555555
}

skinparam UseCase {
BackgroundColor<< HelloWorld >> #FFFFCC
}
(welcome)<< HelloWorld >>
(test)<< HelloWorld >>
(build)<< HelloWorld >>


(build) --> (test) : depend:1
@enduml
