
        @startuml
        
            title HelloWorld
        skinparam arrowFontColor Grey
        
            (welcome)
            
            (test)
            
            (build)
            
            (build) --> (test) : depend:1
        @enduml
    