@startuml

title test
hide stereotype
skinparam Arrow {
Color #555555
FontColor #555555
}
skinparam UseCase {
BackgroundColor #FFFFCC
BorderColor #555555
}

skinparam UseCase {
BackgroundColor<< test >> #FFFFCC
}
(work)<< test >>


@enduml
