@startuml

title FooBar
skinparam ArrowFontColor Black
skinparam ArrowThickness 2
skinparam UseCaseBackgroundColor #FFFECC
skinparam UseCaseBorderColor #333333
skinparam UseCaseBorderThickness 2
skinparam UseCaseFontColor Black

(prepare)
(build)
(dist)


(build) -[#5D9CEC]-> (prepare) : depend:1
(dist) -[#5D9CEC]-> (build) : depend:1

@enduml
